[env:nano_r4]
platform = renesas-ra
board = nano_r4
framework = arduino
board_build.mcu = ra4m1
board_build.f_cpu = 48000000L
build_flags =
    -std=gnu++17
    -DARDUINO_ARCH_RENESAS
    -DARDUINO_NANO_R4_WIFI
build_unflags = -std=gnu++11
extra_scripts = pre:resetDFU.py
platform_packages =
  toolchain-gccarmnoneeabi@~1.90301.0